import React,{createContext,useContext,useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client'; import {BrowserRouter,Link,NavLink,useLocation,useNavigate,useParams} from 'react-router-dom';
import {Menu,Search,ShoppingBag,Heart,User,ArrowRight,Truck,ShieldCheck,RotateCcw,Headphones,Star,Minus,Plus,Trash2,SlidersHorizontal,Check,ChevronDown,Instagram,Facebook,Mail,MapPin} from 'lucide-react'; import './style.css';

type Product={id:string;name:string;category:string;price:number;old?:number;rating:number;reviews:number;image:string;description:string;new?:boolean;sale?:boolean;color:string};
const img=(id:string)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=85`;
const products:Product[]=[
{id:'watch',name:'Minimalist Classic Watch',category:'Accessories',price:149,rating:4.9,reviews:126,color:'Gold',image:img('photo-1524805444758-089113d48a6d'),description:'A refined everyday watch with a warm gold case and precise Japanese movement.',new:true},
{id:'headphones',name:'Studio Wireless Headphones',category:'Electronics',price:89,old:119,rating:4.8,reviews:87,color:'Cream',image:img('photo-1546435770-a3e426bf472b'),description:'Immersive wireless sound wrapped in a considered, comfortable silhouette.',sale:true},
{id:'handbag',name:'Everyday Signature Handbag',category:'Fashion',price:129,rating:4.9,reviews:203,color:'Chestnut',image:img('photo-1584917865442-de89df76afd3'),description:'A beautifully proportioned carryall designed to keep pace with every day.',new:true},
{id:'sneakers',name:'Urban Essential Sneakers',category:'Footwear',price:69,old:89,rating:4.7,reviews:64,color:'Sand',image:img('photo-1542291026-7eec264c27ff'),description:'Cushioned, clean-lined trainers made for easy movement.',sale:true},
{id:'sunglasses',name:'Modern Sunglasses',category:'Accessories',price:45,rating:4.6,reviews:52,color:'Tortoise',image:img('photo-1511499767150-a48a237f0083'),description:'A modern frame with a softly sculpted profile and UV protection.'},
{id:'wallet',name:'Premium Leather Wallet',category:'Accessories',price:59,rating:4.8,reviews:43,color:'Cocoa',image:img('photo-1627123424574-724758594e93'),description:'Compact full-grain leather wallet with thoughtful organization.',new:true},
{id:'shirt',name:'Casual Oversized Shirt',category:'Fashion',price:49,rating:4.7,reviews:75,color:'Ivory',image:img('photo-1603252109303-2751441dd157'),description:'An effortless shirt in a relaxed fit and breathable natural fabric.'},
{id:'crossbody',name:'Everyday Crossbody Bag',category:'Fashion',price:79,rating:4.8,reviews:96,color:'Olive',image:img('photo-1553062407-98eeb64c6a62'),description:'Lightweight, hands-free storage in a polished crossbody form.',new:true},
];
const cats=[['Fashion','4 curated edits','photo-1483985988355-763728e1935b'],['Accessories','18 timeless pieces','photo-1523779917675-b6ed3a42a561'],['Footwear','8 everyday pairs','photo-1543163521-1bf539c55dd2'],['Electronics','12 smart essentials','photo-1496181133206-80ce9b88a853'],['Home & Living','15 calm spaces','photo-1618221195710-dd6b41faaea6'],['Beauty & Wellness','9 daily rituals','photo-1596462502278-27bfdc403348']];
type Store={cart:Record<string,number>;wish:string[];add:(id:string,n?:number)=>void;toggle:(id:string)=>void;setQty:(id:string,n:number)=>void;remove:(id:string)=>void}; const C=createContext<Store>(null!); const useStore=()=>useContext(C);
function Provider({children}:{children:React.ReactNode}) {
  const [cart,setCart]=useState<Record<string,number>>(()=>JSON.parse(localStorage.getItem('rizvi-cart')||'{}'));
  const [wish,setWish]=useState<string[]>(()=>JSON.parse(localStorage.getItem('rizvi-wish')||'[]'));
  useEffect(()=>localStorage.setItem('rizvi-cart',JSON.stringify(cart)),[cart]);
  useEffect(()=>localStorage.setItem('rizvi-wish',JSON.stringify(wish)),[wish]);
  const value:Store={
    cart,wish,
    add:(id,n=1)=>setCart(x=>({...x,[id]:(x[id]||0)+n})),
    toggle:id=>setWish(x=>x.includes(id)?x.filter(a=>a!==id):[...x,id]),
    setQty:(id,n)=>setCart(x=>n<1?Object.fromEntries(Object.entries(x).filter(([k])=>k!==id)):{...x,[id]:n}),
    remove:id=>setCart(x=>Object.fromEntries(Object.entries(x).filter(([k])=>k!==id)))
  };
  return <C.Provider value={value}>{children}</C.Provider>;
}
function Header(){const {cart,wish}=useStore();const [open,setOpen]=useState(false),[q,setQ]=useState('');const nav=useNavigate();const count=Object.values(cart).reduce((a,b)=>a+b,0);const go=(e:React.FormEvent)=>{e.preventDefault();nav('/shop?q='+q)};return <><header><Link className="logo" to="/"><i/>RIZVI <span>STORE</span></Link><nav><NavLink to="/">Home</NavLink><NavLink to="/shop">Shop</NavLink><NavLink to="/categories">Categories</NavLink><NavLink to="/new">New Arrivals</NavLink><NavLink to="/sale">Sale</NavLink><span className="pages">Pages <ChevronDown size={14}/><b><Link to="/about">About Us</Link><Link to="/contact">Contact</Link><a href="#footer">FAQ</a></b></span></nav><form className="search" onSubmit={go}><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products"/></form><div className="tools"><Link to="/wishlist"><Heart/><em>{wish.length}</em></Link><button aria-label="Account"><User/></button><Link to="/cart"><ShoppingBag/><em>{count}</em></Link><button className="mobile-menu" onClick={()=>setOpen(!open)}><Menu/></button></div></header>{open&&<div className="mobile-nav"><NavLink to="/shop">Shop</NavLink><NavLink to="/categories">Categories</NavLink><NavLink to="/new">New Arrivals</NavLink><NavLink to="/sale">Sale</NavLink><NavLink to="/about">About Us</NavLink></div>}</>}
function Footer(){return <footer id="footer"><div className="footer-grid"><div><Link className="logo" to="/"><i/>RIZVI <span>STORE</span></Link><p>Thoughtfully chosen pieces for a life well lived.</p><div className="social"><Instagram/><Facebook/></div></div><div><h4>Quick Links</h4><Link to="/">Home</Link><Link to="/shop">Shop</Link><Link to="/new">New Arrivals</Link><Link to="/sale">Sale</Link></div><div><h4>Customer Care</h4><Link to="/contact">Contact</Link><a href="#footer">FAQs</a><a href="#footer">Shipping Information</a><a href="#footer">Returns & Refunds</a></div><div><h4>Get in Touch</h4><p><Mail/> hello@rizvistore.com</p><p><MapPin/> London · Mon–Fri, 9–6</p></div></div><div className="copyright">© 2026 RIZVI STORE. Made for everyday moments. <span>Terms & Conditions · Privacy Policy</span></div></footer>}
function ProductCard({p}:{p:Product}){const {wish,toggle,add}=useStore();return <article className="product"><Link to={'/product/'+p.id} className="product-img"><img src={p.image} alt={p.name} loading="lazy"/>{p.sale&&<small>SALE</small>}{p.new&&<small className="new">NEW</small>}</Link><button className={'heart '+(wish.includes(p.id)?'liked':'')} onClick={()=>toggle(p.id)} aria-label="Toggle wishlist"><Heart fill={wish.includes(p.id)?'currentColor':'none'}/></button><div className="product-copy"><span>{p.category}</span><Link to={'/product/'+p.id}>{p.name}</Link><div className="price">${p.price} {p.old&&<del>${p.old}</del>}</div><div className="rating"><Star fill="currentColor"/> {p.rating} <i>({p.reviews})</i></div></div><button className="quick" onClick={()=>add(p.id)}>Quick add <Plus size={15}/></button></article>}
const Section=({title,sub,children,link}:{title:string;sub:string;children:React.ReactNode;link?:string})=><section className="section"><div className="section-head"><div><p className="eyebrow">CURATED FOR YOU</p><h2>{title}</h2><p>{sub}</p></div>{link&&<Link className="text-link" to={link}>View all <ArrowRight size={16}/></Link>}</div>{children}</section>;
function Home(){return <><main><section className="hero"><div className="hero-copy"><p className="eyebrow">THE NEW SEASON EDIT</p><h1>Find Your Style.<br/><i>Define Your Everyday.</i></h1><p>Explore thoughtfully selected essentials, modern accessories, and timeless favorites designed for every part of your lifestyle.</p><div className="actions"><Link className="button" to="/shop">Explore Collection <ArrowRight/></Link><Link className="inline" to="/new">Discover New Arrivals</Link></div><div className="people"><div><img src={img('photo-1494790108377-be9c29b29330')}/><img src={img('photo-1534528741775-53994a69daeb')}/><img src={img('photo-1500648767791-00dcc994a43e')}/></div><b>Loved by 12,000+ mindful shoppers</b></div></div><div className="hero-image"><div className="halo"/><img src={img('photo-1584917865442-de89df76afd3')} alt="A crafted leather handbag"/><div className="offer">UP TO<br/><strong>50% OFF</strong></div><div className="leaf">✦</div></div></section><Trust/><Section title="Popular Picks" sub="Everyday favorites chosen for modern living." link="/shop"><div className="product-grid">{products.slice(0,4).map(p=><ProductCard p={p} key={p.id}/>)}</div></Section><Promos/><Section title="Explore Our Collections" sub="Find the pieces that fit your style."><div className="categories">{cats.map(([name,detail,id])=><Link to={'/shop?category='+encodeURIComponent(name)} className="category" key={name}><img src={img(id)} alt={name} loading="lazy"/><div><h3>{name}</h3><p>{detail}</p></div><ArrowRight/></Link>)}</div></Section><Benefits/><Section title="Just Landed" sub="Discover what's new at RIZVI STORE." link="/new"><div className="product-grid">{products.filter(p=>p.new).slice(0,4).map(p=><ProductCard p={p} key={p.id}/>)}</div></Section><Newsletter/></main></>}
function Trust(){const x=[[Truck,'Free Shipping','Complimentary delivery on qualifying orders.'],[ShieldCheck,'Secure Payments','Shop confidently with protected checkout.'],[RotateCcw,'Easy Returns','Simple returns within 30 days.'],[Headphones,'Customer Support',"We're here whenever you need assistance."]];return <section className="trust">{x.map(([I,h,d]:any)=>{const Icon=I;return <div key={h}><Icon/><p><b>{h}</b><span>{d}</span></p></div>})}</section>}
function Promos(){return <section className="promos"><div className="promo peach"><div><p className="eyebrow">LIMITED-TIME OFFER</p><h2>A Little More Style,<br/>For Less.</h2><strong>UP TO 50% OFF</strong><Link to="/sale">Shop the Sale <ArrowRight/></Link></div><img src={img('photo-1485230895905-ec40ba36b9bc')} alt="Seasonal fashion" loading="lazy"/></div><div className="promo sage"><div><p className="eyebrow">JUST ARRIVED</p><h2>Fresh Finds for<br/>Your Everyday.</h2><Link to="/new">Explore New Arrivals <ArrowRight/></Link></div><img src={img('photo-1594223274512-ad4803739b7c')} alt="New accessories" loading="lazy"/></div></section>}
function Benefits(){const items=[['Thoughtful Quality','Discover products selected with quality and everyday usefulness in mind.'],['Fair Prices','Enjoy great value across our carefully selected collections.'],['Shopping You Can Trust','Transparent product information and secure transactions.'],['Reliable Delivery','Convenient delivery options and helpful order updates.']];return <section className="benefit-wrap"><div className="section-head"><div><p className="eyebrow">THE RIZVI DIFFERENCE</p><h2>A Better Way to Shop</h2></div></div><div className="benefits">{items.map(([h,p],i)=><div key={h}><span>0{i+1}</span><h3>{h}</h3><p>{p}</p></div>)}</div></section>}
function Newsletter(){const [v,setV]=useState(''),[done,setDone]=useState(false);return <section className="newsletter"><div><p className="eyebrow">STAY IN THE KNOW</p><h2>A Little Inspiration<br/>in Your Inbox</h2><p>Sign up for new arrivals, exclusive offers, and thoughtful updates from RIZVI STORE.</p></div><form onSubmit={e=>{e.preventDefault();if(/^\S+@\S+\.\S+$/.test(v))setDone(true)}}>{done?<strong><Check/> You’re on the list. Welcome!</strong>:<><input aria-label="Email address" type="email" value={v} onChange={e=>setV(e.target.value)} placeholder="Your email address" required/><button>Subscribe <ArrowRight/></button><small>We respect your inbox. Unsubscribe anytime.</small></>}</form></section>}
function Shop({mode}:{mode?:'sale'|'new'}){const loc=useLocation();const qs=new URLSearchParams(loc.search);const [category,setCategory]=useState(qs.get('category')||'All');const [q,setQ]=useState(qs.get('q')||'');const [sort,setSort]=useState('featured');const shown=useMemo(()=>products.filter(p=>(category==='All'||p.category===category)&&(mode==='sale'?!p.sale:true)&&(mode==='new'?!p.new:true)&&(`${p.name} ${p.category} ${p.description}`).toLowerCase().includes(q.toLowerCase())).sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:0),[category,q,sort,mode]);const title=mode==='sale'?'Seasonal Sale':mode==='new'?'New Arrivals':'Shop All Products';return <main className="page"><div className="page-title"><p>Home / {title}</p><h1>{title}</h1><span>{mode==='sale'?'A considered edit of exceptional finds, now at gentler prices.':mode==='new'?'The latest thoughtful finds, freshly added to our collection.':'Everyday objects and style essentials, selected with intention.'}</span></div>{mode==='sale'&&<div className="sale-bar">MID-SEASON EVENT <b>Up to 50% off selected pieces</b><Link to="/shop">Explore all</Link></div>}<div className="shop-layout"><aside><h3>Filter products</h3><label>Search<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search the collection"/></label><b>Category</b>{['All',...cats.map(c=>c[0])].map(c=><button className={category===c?'selected':''} onClick={()=>setCategory(c)} key={c}>{c}</button>)}<b>Availability</b><label className="check"><input type="checkbox"/> In stock</label><button className="clear" onClick={()=>{setCategory('All');setQ('')}}>Clear filters</button></aside><div className="listing"><div className="list-tools"><span>{shown.length} pieces found</span><label>Sort <select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></label></div>{shown.length?<div className="product-grid">{shown.map(p=><ProductCard p={p} key={p.id}/>)}</div>:<div className="empty"><Search/><h2>No pieces found</h2><p>Try a different search or clear your filters.</p></div>}</div></div></main>}
function Detail(){const {id=''}=useParams();const p=products.find(x=>x.id===id)||products[0];const {add,wish,toggle}=useStore();const [qty,setQty]=useState(1),[tab,setTab]=useState('Description');return <main className="page detail"><div className="breadcrumbs">Home / Shop / {p.name}</div><div className="detail-main"><div className="gallery"><img src={p.image} alt={p.name}/><div><img src={p.image} alt="Product view"/><img src={p.image} alt="Product detail"/></div></div><div className="detail-copy"><p className="eyebrow">{p.category}</p><h1>{p.name}</h1><div className="rating"><Star fill="currentColor"/> {p.rating} <i>({p.reviews} reviews)</i></div><div className="detail-price">${p.price} {p.old&&<del>${p.old}</del>}</div><p>{p.description}</p><hr/><b>Colour: <span>{p.color}</span></b><div className="swatches"><button className="brown"/><button className="olive"/><button className="cream"/></div>{p.category==='Fashion'||p.category==='Footwear'?<><b>Size</b><div className="sizes"><button>S</button><button className="active">M</button><button>L</button><button>XL</button></div></>:null}<div className="buyrow"><div className="quantity"><button onClick={()=>setQty(Math.max(1,qty-1))}><Minus/></button>{qty}<button onClick={()=>setQty(qty+1)}><Plus/></button></div><button className="button" onClick={()=>add(p.id,qty)}>Add to Cart <ShoppingBag/></button><button className={'heart big '+(wish.includes(p.id)?'liked':'')} onClick={()=>toggle(p.id)}><Heart fill={wish.includes(p.id)?'currentColor':'none'}/></button></div><Link className="buy-now" to="/checkout" onClick={()=>add(p.id,qty)}>Buy now</Link><div className="delivery"><Truck/> Free shipping on orders over $75 · Easy 30-day returns</div></div></div><div className="tabs"><div>{['Description','Specifications','Shipping & Returns'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</div><p>{tab==='Description'?p.description+' Made in small, considered batches with an eye toward beautiful utility.':tab==='Specifications'?'Materials: premium selected materials. Care: clean gently with a soft dry cloth.':"Orders are packed within 1–2 business days. Eligible purchases can be returned within 30 days of delivery."}</p></div><Section title="You may also like" sub="More pieces we think you’ll love."><div className="product-grid">{products.filter(x=>x.id!==p.id).slice(0,4).map(x=><ProductCard p={x} key={x.id}/>)}</div></Section></main>}
function Cart(){const {cart,setQty,remove}=useStore();const items=products.filter(p=>cart[p.id]);const sub=items.reduce((a,p)=>a+p.price*cart[p.id],0);return <main className="page"><div className="page-title"><p>Home / Shopping Bag</p><h1>Your Shopping Bag</h1></div>{!items.length?<Empty icon={<ShoppingBag/>} title="Your bag is waiting" action="Explore the collection" to="/shop"/>:<div className="cart-layout"><div className="cart-items">{items.map(p=><article className="cart-item"><img src={p.image} alt={p.name}/><div><p>{p.category}</p><h3>{p.name}</h3><span>${p.price}</span><button onClick={()=>remove(p.id)}><Trash2/> Remove</button></div><div className="quantity"><button onClick={()=>setQty(p.id,cart[p.id]-1)}><Minus/></button>{cart[p.id]}<button onClick={()=>setQty(p.id,cart[p.id]+1)}><Plus/></button></div><strong>${p.price*cart[p.id]}</strong></article>)}</div><OrderBox sub={sub}/></div>}</main>}
function OrderBox({sub}:{sub:number}){const ship=sub>75?0:9;return <aside className="order"><h2>Order Summary</h2><p>Subtotal <b>${sub}</b></p><p>Estimated shipping <b>{ship?'$'+ship:'Free'}</b></p><hr/><h3>Total <b>${sub+ship}</b></h3><input placeholder="Discount code"/><button className="button">Apply</button><Link className="checkout" to="/checkout">Proceed to Checkout <ArrowRight/></Link><Link className="continue" to="/shop">← Continue Shopping</Link></aside>}
function Wishlist(){const {wish,add,toggle}=useStore();const items=products.filter(p=>wish.includes(p.id));return <main className="page"><div className="page-title"><p>Home / Wishlist</p><h1>Saved for Later</h1><span>Your personal edit of pieces you love.</span></div>{items.length?<div className="product-grid">{items.map(p=><ProductCard p={p} key={p.id}/>)}</div>:<Empty icon={<Heart/>} title="Your wishlist is beautifully empty" action="Discover pieces to love" to="/shop"/>}</main>}
function Empty({icon,title,action,to}:{icon:React.ReactNode;title:string;action:string;to:string}){return <div className="empty">{icon}<h2>{title}</h2><p>Explore our thoughtful collection and find something just right.</p><Link className="button" to={to}>{action}<ArrowRight/></Link></div>}
function Checkout(){const {cart}=useStore();const [done,setDone]=useState(false);const items=products.filter(p=>cart[p.id]);const sub=items.reduce((a,p)=>a+p.price*cart[p.id],0);if(done)return <main className="page"><Empty icon={<Check/>} title="Order received — thank you" action="Continue shopping" to="/shop"/></main>;return <main className="page"><div className="page-title"><p>Shopping Bag / Checkout</p><h1>Checkout</h1></div><div className="checkout-layout"><form className="checkout-form" onSubmit={e=>{e.preventDefault();setDone(true)}}><h2>Contact information</h2><label>Email address<input type="email" required placeholder="you@example.com"/></label><h2>Delivery address</h2><div className="two"><label>First name<input required/></label><label>Last name<input required/></label></div><label>Address<input required placeholder="Street address"/></label><div className="two"><label>City<input required/></label><label>Postcode<input required/></label></div><h2>Delivery method</h2><label className="radio"><input type="radio" name="shipping" defaultChecked/> Standard delivery <b>Free</b></label><label className="radio"><input type="radio" name="shipping"/> Express delivery <b>$12</b></label><h2>Payment</h2><label className="radio"><input type="radio" name="pay" defaultChecked/> Card ending in ···· <b>Demo only</b></label><button className="button">Place demo order <ArrowRight/></button><small>This is a frontend demonstration; no payment will be processed.</small></form><OrderBox sub={sub}/></div></main>}
function Informational({page}:{page:'about'|'contact'|'categories'}){if(page==='categories')return <main className="page"><div className="page-title"><p>Home / Collections</p><h1>Explore Our Collections</h1><span>Beautifully useful pieces for every part of your day.</span></div><div className="categories large">{cats.map(([name,detail,id])=><Link to={'/shop?category='+encodeURIComponent(name)} className="category" key={name}><img src={img(id)} alt={name}/><div><h3>{name}</h3><p>{detail}</p></div><ArrowRight/></Link>)}</div></main>;if(page==='about')return <main className="page about"><div className="about-img"><img src={img('photo-1441986300917-64674bd600d8')} alt="Rizvi store interior"/></div><div><p className="eyebrow">OUR POINT OF VIEW</p><h1>Designed for the way you really live.</h1><p>RIZVI STORE is a modern edit of wardrobe, home, and everyday essentials. We believe thoughtful choices can make the ordinary feel extraordinary.</p><p>Our small, considered collection is chosen for longevity, ease, and a quietly confident point of view.</p><Link className="button" to="/shop">Explore our edit <ArrowRight/></Link></div></main>;return <main className="page contact"><div className="page-title"><p>Home / Contact</p><h1>We’d love to hear from you.</h1><span>Have a question about an order or a product? Our small team is here.</span></div><div className="contact-grid"><div><h2>Get in touch</h2><p><Mail/> hello@rizvistore.com</p><p><Headphones/> Monday–Friday, 9am–6pm GMT</p><p><MapPin/> London, United Kingdom</p></div><form onSubmit={e=>{e.preventDefault();alert('Thank you — your message is ready for our team.')}}><label>Name<input required placeholder="Your name"/></label><label>Email<input required type="email" placeholder="you@example.com"/></label><label>Message<textarea required placeholder="How can we help?"/></label><button className="button">Send message <ArrowRight/></button></form></div></main>}
function App(){return <Provider><Header/><Routes/></Provider>} function Routes(){const location=useLocation();useEffect(()=>window.scrollTo(0,0),[location.pathname]);let c=location.pathname==='/'?<Home/>:location.pathname==='/shop'?<Shop/>:location.pathname==='/sale'?<Shop mode="sale"/>:location.pathname==='/new'?<Shop mode="new"/>:location.pathname.startsWith('/product/')?<Detail/>:location.pathname==='/cart'?<Cart/>:location.pathname==='/checkout'?<Checkout/>:location.pathname==='/wishlist'?<Wishlist/>:location.pathname==='/about'?<Informational page="about"/>:location.pathname==='/contact'?<Informational page="contact"/>:<Informational page="categories"/>;return <>{c}<Footer/></>};createRoot(document.getElementById('root')!).render(<BrowserRouter><App/></BrowserRouter>);
